---
version: "2"
plugins:
  pylint:
    enabled: true
    exclude_patterns:
      - "**/*"
      - "!fdroid"
      - "!makebuildserver"
      - "!setup.py"
      - "!fdroidserver/*.py"
      - "!tests/*.py"
      - "!tests/*.TestCase"

  shellcheck:
    enabled: true
    # Only include tests/run-tests
    exclude_patterns:
      - "**/*"
      - "!tests/run-tests"

  bandit:
    enabled: true

  # Disable as they are not among the array of linters we used previously
  duplication:
    enabled: false

  structure:
    enabled: false
