---
version: "2"
plugins:
  pylint:
    enabled: true

  shellcheck:
    enabled: true

  bandit:
    enabled: true

  # Disable as they are not among the array of linters we used previously
  duplication:
    enabled: false

  structure:
    enabled: false
