---
version: "2"
plugins:
  shellcheck:
    enabled: true
    # Only include tests/run-tests
    exclude_patterns:
      - "**/*"
      - "!tests/run-tests"
    checks:
      SC2046:
        enabled: false
      SC2090:
        enabled: false
    issue_override:
      severity: "major"

  bandit:
    enabled: true

  # Disable as they are not among the array of linters we used previously
  duplication:
    enabled: false

  structure:
    enabled: false
