#!/bin/bash

if [ `dirname $0` != "." ]; then
    echo "only run this script like ./`basename $0`"
    exit
fi

if [ -z $WORKSPACE ]; then
    WORKSPACE=`pwd`
fi

# make sure that no VirtualBox processes are left running
cleanup_all() {
    echo "$(date -u) - cleanup in progress..."
    ps auxww|grep VBox
    cd $WORKSPACE/buildserver
    vagrant halt || true
    sleep 5
    killall VBoxHeadless || true
    sleep 5
    killall -9 VBoxHeadless || true
    echo "$(date -u) - cleanup done."
    host repo1.maven.org || true
    host jcenter.bintray.com || true
}
trap cleanup_all INT TERM EXIT

set -e
set -x

# make sure we have the vagrant box image cached
test -e ~/.cache/fdroidserver || mkdir -p ~/.cache/fdroidserver
cd ~/.cache/fdroidserver
wget --tries=1 --timeout=5 --continue https://f-droid.org/jessie32.box || true
echo "ff6b0c0bebcb742783becbc51a9dfff5a2a0a839bfcbfd0288dcd3113f33e533  jessie32.box" > jessie32.box.sha256
sha256sum -c jessie32.box.sha256

# redirect homes to be in the git repo, so they'll get cleaned and reset
export XDG_CONFIG_HOME=$WORKSPACE
export VBOX_USER_HOME=$WORKSPACE/VirtualBox
mkdir $VBOX_USER_HOME
VBoxManage setproperty machinefolder $WORKSPACE/virtualbox.d
VBoxManage setproperty logginglevel debug
export VAGRANT_HOME=$WORKSPACE/vagrant.d
mkdir $VAGRANT_HOME

cd $WORKSPACE
echo "debian_mirror = 'http://ftp.uk.debian.org/debian/'" > $WORKSPACE/makebuildserver.config.py
echo "boot_timeout = 1200" >> $WORKSPACE/makebuildserver.config.py
echo "apt_package_cache = True" >> $WORKSPACE/makebuildserver.config.py
echo "copy_caches_from_host = True" >> $WORKSPACE/makebuildserver.config.py
./makebuildserver --verbose

# copy existing gradle and m2 caches on the host to the guest
cd $WORKSPACE/buildserver
vagrant up
cd ~
for d in .m2 .gradle/caches .gradle/wrapper; do
    if [ -d $d ]; then
        vagrant ssh -c "mkdir -p ~/$d"
        rsync -axv --progress --delete \
            -e "ssh -i ${VAGRANT_HOME}/insecure_private_key -p2222 -oIdentitiesOnly=yes" \
            $d/ "vagrant@127.0.0.1:$d/"
    fi
done

# this file changes every time but should not be cached
vagrant ssh -c "rm -f ~/.gradle/caches/modules-2/modules-2.lock"
vagrant ssh -c "rm -fr ~/.gradle/caches/*/plugin-resolution/"


# now get the metadata to build
cd $WORKSPACE
if [ -e fdroiddata ]; then
    cd fdroiddata
    git checkout master
    git pull
    cd ..
else
    git clone --depth 1 https://gitlab.com/fdroid/fdroiddata.git fdroiddata
fi

cd fdroiddata
echo "build_server_always = True" > config.py
# if it can't build fdroid, then its really broken
../fdroid build --verbose --stop --latest org.fdroid.fdroid
# Gradle, JNI, preassemble
../fdroid build --verbose --stop org.adaway:55
# Gradle with retrolambda (JDK7 and JDK8)
../fdroid build --verbose --stop com.moez.QKSMS:124
# Maven
../fdroid build --verbose --stop org.quantumbadger.redreader:55
# Custom build (make)
#../fdroid build --verbose --stop com.amaze.filemanager:29
# Uses verification
#../fdroid build --verbose --stop info.guardianproject.checkey:101
