sdk_path: /home/vagrant/android-sdk
ndk_paths:
  r10e: /home/vagrant/android-ndk/r10e
  r21e: /home/vagrant/android-ndk/r21e
  r22b: /home/vagrant/android-ndk/r22b

java_paths:
  8: /usr/lib/jvm/java-8-openjdk-amd64

gradle_version_dir: /opt/gradle/versions
