#!/bin/bash

cat > /etc/rc.local  << EOF
#!/bin/bash

if [ -x /opt/firstrun.sh ] ; then
	/opt/firstrun.sh &> /var/log/firstrun.log || true
	rm -f /opt/firstrun.sh
fi
EOF

chmod 0755 /etc/rc.local

cat > /opt/firstrun.sh << EOF
#!/bin/bash

mkdir -p /home/vagrant/.ssh
# Well known vagrant key
echo ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== > /home/vagrant/.ssh/authorized_keys

chown -R vagrant:vagrant /home/vagrant/.ssh
chmod 0600 /home/vagrant/.ssh/authorized_keys

dpkg-reconfigure openssh-server
systemctl restart ssh

EOF

chmod 0755 /opt/firstrun.sh
