#!/bin/sh
#
# Sets up environment (variables and configuration options) for the build
# process. All other provisioning scripts are called after this one.
#

set -e
set -x

# set global variables
cat << EOF > /etc/profile.d/bsenv.sh
# generated on $(date)
export ANDROID_HOME=$1
export PATH=\$PATH:\$ANDROID_HOME/tools:\$ANDROID_HOME/platform-tools:/opt/gradle/bin
EOF

# make sure that SSH never hangs at a password or key prompt
printf '    StrictHostKeyChecking yes' >> /etc/ssh/ssh_config
printf '    BatchMode yes' >> /etc/ssh/config
